import localFont from "next/font/local";
import "./globals.css";
const halenoir = localFont({
  src: [{
    path: './fonts/HalenoirCompact-Medium.otf',
    weight: '400',
    style: 'normal'
  },
  {
    path: './fonts/Halenoir-DemiBold.otf',
    weight: '600',
    style: 'normal'
  },{
    path: './fonts/Halenoir-Bold.otf',
    weight: '700',
    style: 'normal'
  }],
  variable: '--font-halenoir'

})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${halenoir.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
